### PR TITLE
Parallel path and a slight change in mode expansion code in system.py

### PR DESCRIPTION
**Pull request by sainag2473**
Parallel path to system.py that handles sparse matrices have guyan, sos_modal and mode expansion functions working. I have also added a line of code to mode expansion function in system.py to avoid reshape error.

### CODE REVIEW

**Comment by sainag2473** [comment]
I will keep updating with examples and other codes,

**Comment by sainag2473** [comment]
So, is this my function, but with you updating it to handle sparse matrices? If so, you should also put your name up in author.

Yes, system.py is your function and I am updating it to handle sparse matrices by creating new module (parallel path). I will updated the file with the author info.

**Comment by sainag2473** [comment]
>> So, is this my function, but with you updating it to handle sparse matrices? If so, you should also put your name up in author.
 
 Yes, system.py is your function and I am updating it to handle sparse matrices by creating new module (parallel path). I will updated the file with the author info.

**Comment by sainag2473** [comment]
>> I'm confused... where is this file?

I'm sorry for the confusion. Please follow the link for the file which contains the comparison of results between vt.system module and vt.sparsematriceshandler module (parallel path) : https://github.com/sainag2473/vibrationtesting/blob/9c9c5b080898acbfb20d57b3b005e3f2253a7cb4/JupyterNotebooks/Testing_working_funcitions_in_sparsematriceshandler.ipynb

Regarding scipy's issue using scipy.sparse,linalg.eigsh is resolved as suggested by Scipy. Issue was
[omega,zeta,Psi] = vt.sos_modal_forsparse(Mred,Kred)
Psi.shape gives (74,75). It's resolved now as you will see in the notebook.

>> I don't see a pull request. Is it in your copy?

**Comment by sainag2473** [comment]
Hello Dr. Slater

I am sorry once again I think I have to do more tests before I pull request. So I am closing the pull request once again. I apologize for my impatience.

Thanks,
Sainag.

**Comment by josephcslater** [comment]
Please look at 
vibrationtesting/vibrationtesting/tests/test_vibrationtesting.py and make sure you have a series of good unit tests there. It will help ensure you have good code.

**Comment by sainag2473** [comment]
> Please look at
> vibrationtesting/vibrationtesting/tests/test_vibrationtesting.py and make sure you have a series of good unit tests there. It will help ensure you have good code.

Thanks Dr. Slater, I will follow your suggestion.

**Pull request closed without merging**
